#!/usr/bin/env bash
# setup.sh: validate prerequisites and create a ready-to-use venv.
#
# Usage:
#   bash setup.sh          # creates .venv/, installs deps, writes .env
#   source .env            # loads PYSPARK_PYTHON etc. into your shell
#
# After setup, all make targets work without extra env vars:
#   make stage
#   make features
#   make benchmark

set -euo pipefail

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[ok]${NC}  $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
fail() { echo -e "${RED}[fail]${NC} $*"; exit 1; }

echo "=== AML FHE pipeline setup ==="
echo

# ── 1. Python 3.10 ───────────────────────────────────────────────────────────
PY310=""
for candidate in python3.10 python3 python; do
    if command -v "$candidate" &>/dev/null; then
        ver=$("$candidate" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        if [[ "$ver" == "3.10" ]]; then
            PY310=$(command -v "$candidate")
            break
        fi
    fi
done

if [[ -z "$PY310" ]]; then
    fail "Python 3.10 not found. concrete-ml requires Python 3.10 exactly.
  Install it with:
    sudo apt install python3.10 python3.10-venv   # Ubuntu/Debian
    brew install python@3.10                       # macOS"
fi
ok "Python 3.10 found: $PY310"

# ── 2. Java 11 ───────────────────────────────────────────────────────────────
if ! command -v java &>/dev/null; then
    fail "Java not found. PySpark 3.5.x requires Java 11.
  Install it with:
    sudo apt install openjdk-11-jdk   # Ubuntu/Debian
    brew install openjdk@11           # macOS"
fi

JAVA_VER=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d. -f1)
if [[ "$JAVA_VER" -lt 11 ]]; then
    fail "Java $JAVA_VER found but Java 11 is required. PySpark 3.5.x does not support Java < 11."
fi
if [[ "$JAVA_VER" -gt 11 ]]; then
    warn "Java $JAVA_VER found. PySpark 3.5.x is tested against Java 11.
       If staging fails, switch your JAVA_HOME to a Java 11 installation."
else
    ok "Java 11 found: $(java -version 2>&1 | head -1)"
fi

# ── 3. Kaggle credentials ─────────────────────────────────────────────────────
if [[ ! -f "$HOME/.kaggle/kaggle.json" ]]; then
    warn "~/.kaggle/kaggle.json not found.
       'make data-download' will fail until credentials are in place.
       To set up:
         1. Log in at kaggle.com -> Account -> API -> 'Create new token'
         2. mv ~/Downloads/kaggle.json ~/.kaggle/kaggle.json
         3. chmod 600 ~/.kaggle/kaggle.json"
else
    ok "Kaggle credentials found"
fi

# ── 4. Create venv ────────────────────────────────────────────────────────────
VENV_DIR=".venv"
if [[ -d "$VENV_DIR" ]]; then
    existing_py=$("$VENV_DIR/bin/python" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "unknown")
    if [[ "$existing_py" != "3.10" ]]; then
        warn "Existing .venv uses Python $existing_py, not 3.10. Recreating."
        rm -rf "$VENV_DIR"
    else
        ok "Existing .venv is Python 3.10, reusing"
    fi
fi

if [[ ! -d "$VENV_DIR" ]]; then
    echo "Creating .venv with $PY310..."
    "$PY310" -m venv "$VENV_DIR"
    ok ".venv created"
fi

VENV_PY="$(pwd)/$VENV_DIR/bin/python"

# ── 5. Install dependencies ───────────────────────────────────────────────────
echo "Installing dependencies (this may take a few minutes)..."
"$VENV_PY" -m pip install --upgrade pip --quiet
"$VENV_PY" -m pip install -e . --quiet
ok "Dependencies installed"

# ── 6. Verify critical imports ────────────────────────────────────────────────
echo "Verifying critical imports..."
"$VENV_PY" -c "from concrete.ml.sklearn import XGBClassifier" 2>/dev/null \
    && ok "concrete-ml importable" \
    || fail "concrete-ml import failed. Check that concrete-ml==1.9.0 installed correctly for Python 3.10."

"$VENV_PY" -c "import pyspark" 2>/dev/null \
    && ok "pyspark importable" \
    || fail "pyspark import failed. Check pyproject.toml dependencies."

"$VENV_PY" -c "import igraph, leidenalg" 2>/dev/null \
    && ok "igraph + leidenalg importable" \
    || fail "igraph or leidenalg import failed."

# ── 7. Write .env ─────────────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by setup.sh. Source this file before running make stage / make features.
# Or add 'source .env' to your shell profile while working in this repo.
export VENV_PY="$VENV_PY"
export PYTHON="$VENV_PY"
export PYTHONPATH="$(pwd)/src"
export PYSPARK_PYTHON="$VENV_PY"
export PYSPARK_DRIVER_PYTHON="$VENV_PY"
EOF
ok ".env written"

# ── 8. Summary ────────────────────────────────────────────────────────────────
echo
echo "=== Setup complete ==="
echo
echo "Activate for this session:"
echo "  source .env"
echo
echo "Then run:"
echo "  make data-download    # download ~7.6 GB Kaggle dataset"
echo "  make data-validate    # confirm raw files"
echo "  make stage            # ~20-40 min Spark job"
echo "  make features         # ~2.5 hr Spark job, needs ~62 GB free RAM"
echo "  make benchmark        # XGBoost + FHE evaluation"
echo
echo "Or all at once:"
echo "  make full"
